### ISSUE TITLE
Certificate error when trying to login

### ISSUE THREAD

**Issue by F3yl1x** [blue1stone/python-bring-api#18]
I got a certificate warning when trying to access bring. I could bypass it by changing the url to 'http://api.getbring.com/rest/v2/' so without ssl.

Traceback (most recent call last):
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/connector.py", line 1116, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 1188, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ssl_shutdown_timeout=ssl_shutdown_timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 1221, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/sslproto.py", line 581, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/sslproto.py", line 563, in _do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/ssl.py", line 951, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/python_bring_api/bring.py", line 113, in loginAsync
    async with self._session.post(url, data=data) as r:
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/client.py", line 701, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/connector.py", line 1394, in _create_direct_connection
    raise last_exc
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/aiohttp/connector.py", line 1118, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.getbring.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1018)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/API.py", line 386, in <module>
    bring.login()
    ~~~~~~~~~~~^^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/python_bring_api/bring.py", line 85, in login
    return asyncio.run(_async())
           ~~~~~~~~~~~^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/python_bring_api/bring.py", line 82, in _async
    res = await self.loginAsync()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/f3yl1x/Documents/01_Privat/07_Code/HomeAI/venv/lib/python3.13/site-packages/python_bring_api/bring.py", line 138, in loginAsync
    raise BringRequestException(f'Authentication failed due to request exception.') from e
python_bring_api.exceptions.BringRequestException: Authentication failed due to request exception.

**Comment by eliasball** [comment]
Hi! This does not happen for me in my network, so I am guessing it is an error with your local network. Therefore I sadly do not know what could be the cause of it, sorry.
Maybe you will have some luck googling with regards to the `aiohttp` library which actually makes the API call. Hope you can find a solution!
